"""admin_users table (P0-05 §2.19.6)

Revision ID: e2de76ea9934
Revises: bb11c89a96bd
Create Date: 2026-07-29 02:03:25.167620+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2de76ea9934"
down_revision: str | None = "bb11c89a96bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_encrypted", sa.String(length=256), nullable=False),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "funds",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("sub_type", sa.String(length=32), nullable=True),
        sa.Column("theme", sa.String(length=32), nullable=True),
        sa.Column("style", sa.String(length=16), nullable=True),
        sa.Column("launch_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index("ix_funds_type_theme", "funds", ["type", "theme"], unique=False)
    op.create_table(
        "paper_accounts",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column(
            "init_capital",
            sa.Numeric(precision=18, scale=2),
            server_default=sa.text("1000000"),
            nullable=False,
        ),
        sa.Column("cash", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "holdings",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("stock_code", sa.String(length=12), nullable=False),
        sa.Column("stock_name", sa.String(length=64), nullable=True),
        sa.Column("weight", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["code"], ["funds.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code", "report_date", "stock_code"),
    )
    op.create_table(
        "navs",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("nav", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("acc_nav", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("adj_nav", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["code"], ["funds.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code", "trade_date"),
    )
    op.create_index("ix_navs_date", "navs", ["trade_date"], unique=False)
    op.create_table(
        "paper_positions",
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("shares", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.account_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["code"], ["funds.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "code"),
    )
    op.create_table(
        "paper_trades",
        sa.Column("trade_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("shares", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("nav", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("side IN ('buy','sell')", name="ck_paper_trades_side"),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.account_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["code"],
            ["funds.code"],
        ),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index("ix_trades_account", "paper_trades", ["account_id", "trade_date"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("portfolio_id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('template','manual','import')", name="ck_portfolios_source"),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("portfolio_id"),
    )
    op.create_table(
        "research_metrics",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("alpha", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("beta", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("tracking_error", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("info_ratio", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("peg", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("erp", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("peg_available", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("erp_available", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("cv_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["code"], ["funds.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "scores",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("window", sa.String(length=8), server_default=sa.text("'3y'"), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("composite", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["code"], ["funds.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "portfolio_weights",
        sa.Column("portfolio_id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("weight", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["code"],
            ["funds.code"],
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.portfolio_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("portfolio_id", "code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_weights")
    op.drop_table("scores")
    op.drop_table("research_metrics")
    op.drop_table("portfolios")
    op.drop_index("ix_trades_account", table_name="paper_trades")
    op.drop_table("paper_trades")
    op.drop_table("paper_positions")
    op.drop_index("ix_navs_date", table_name="navs")
    op.drop_table("navs")
    op.drop_table("holdings")
    op.drop_table("paper_accounts")
    op.drop_index("ix_funds_type_theme", table_name="funds")
    op.drop_table("funds")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
